package com.lumi.galeria

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.lumi.galeria.data.WORDS

/** En qué idioma habla la app. */
enum class AppLanguage(val label: String) { SYSTEM("El del teléfono"), SPANISH("Español"), ENGLISH("English") }

/**
 * Los textos de la app están escritos en español dentro del código. Cuando toca enseñarlos en
 * inglés se traducen justo antes de pintarlos, con [tr]: así un mismo texto vale para los dos
 * idiomas y añadir otro es escribir otra tabla como [EN].
 */
object Lang {
    var english by mutableStateOf(false)
        private set

    fun apply(choice: AppLanguage) {
        english = when (choice) {
            AppLanguage.SPANISH -> false
            AppLanguage.ENGLISH -> true
            // Con el teléfono en cualquier idioma que no sea español, inglés.
            AppLanguage.SYSTEM -> android.content.res.Resources.getSystem().configuration.locales[0].language != "es"
        }
    }
}

private val cache = java.util.concurrent.ConcurrentHashMap<String, String>()

/** [text] en el idioma de la app. Lo que no tiene traducción se deja como está. */
fun tr(text: String): String {
    if (!Lang.english || text.isEmpty()) return text
    cache[text]?.let { return it }
    val out = translate(text)
    if (cache.size < 4000) cache[text] = out
    return out
}

private fun translate(text: String): String {
    EN[text]?.let { return it }
    for ((pattern, build) in PATTERNS) {
        val match = pattern.matchEntire(text) ?: continue
        return build(match.groupValues)
    }
    // Varias piezas unidas con un punto medio: cada una por su cuenta.
    if (" · " in text) return text.split(" · ").joinToString(" · ") { translate(it) }
    // Una cosa reconocida en la foto ("perro"), que el modelo ya nombra en inglés.
    thing(text)?.let { return it }
    // Varias cosas seguidas ("perro, playa").
    if (", " in text) {
        val parts = text.split(", ").map { thing(it) ?: return text }
        return parts.joinToString(", ")
    }
    return text
}

/** Palabra en español de cada cosa que reconoce el modelo -> su nombre en inglés. */
private val THINGS: Map<String, String> by lazy {
    HashMap<String, String>().apply { WORDS.forEach { (label, words) -> words.firstOrNull()?.let { putIfAbsent(it, label.lowercase()) } } }
}

private fun thing(text: String): String? {
    val found = THINGS[text.lowercase()] ?: return null
    return if (text.first().isUpperCase()) found.replaceFirstChar { it.uppercase() } else found
}

private fun rule(pattern: String, build: (List<String>) -> String) = Regex(pattern) to build

/** Textos con un dato dentro (un número, un nombre, un tamaño). */
private val PATTERNS: List<Pair<Regex, (List<String>) -> String>> = listOf(
    rule("Hace (\\d+) años") { "${it[1]} years ago" },
    rule("No hay fotos ni vídeos en «(.+)»") { "No photos or videos in “${it[1]}”" },
    rule("Importar (\\d+) a «(.+)»") { "Import ${it[1]} to “${it[2]}”" },
    rule("Nada en (\\d+)") { "Nothing in ${it[1]}" },
    rule("Marcaste (.+) este año\\.") { "You marked ${it[1]} this year." },
    rule("Guardando el vídeo nuevo… (\\d+) %") { "Saving the new video… ${it[1]}%" },
    rule("Guardando (\\d+) %") { "Saving ${it[1]}%" },
    rule("Dura (.+) con la velocidad elegida") { "Lasts ${it[1]} at the chosen speed" },
    rule("Dura (.+)") { "Lasts ${it[1]}" },
    rule("Cámara lenta: (.+)") { "Slow motion: ${it[1]}" },
    rule("Más rápido: (.+)") { "Faster: ${it[1]}" },
    rule("Volumen: (\\d+) %") { "Volume: ${it[1]}%" },
    rule("No es (.+)") { "Not ${it[1]}" },
    rule("Quitadas de (.+)") { "Removed from ${it[1]}" },
    rule("Buscando caras: (.+) de (.+) fotos") { "Finding faces: ${it[1]} of ${it[2]} photos" },
    rule("Lo mejor de (.+)") { "Best of ${it[1].replaceFirstChar(Char::uppercase)}" },
    rule("Mover (\\d+) aquí") { "Move ${it[1]} here" },
    rule("Mover (\\d+) a la papelera") { "Move ${it[1]} to the trash" },
    rule("Devolver (\\d+) a la galería") { "Return ${it[1]} to the gallery" },
    rule("Copiando (\\d+) de (\\d+)") { "Copying ${it[1]} of ${it[2]}" },
    rule("(.+) sin copiar") { "${it[1]} not backed up" },
    rule("(.+ (?:copied|moved|imported|exported)) a (.+)") { "${it[1]} to ${translate(it[2])}" },
    rule("(.+ returned) a la galería") { "${it[1]} to the gallery" },
    rule("Última copia: (.+)") { "Last backup: ${it[1]}" },
    rule("Nada con «(.*)»") { "Nothing for “${it[1]}”" },
    rule("(.+)\\. Lumi no distingue «(.+)»: te enseña lo más parecido que reconoce\\.") {
        "${it[1]}. Lumi can't tell “${it[2]}” apart: it shows the closest thing it recognizes."
    },
    rule("Lumi ha mirado (\\d+) de (.+)\\. Ya puedes buscar en esas\\.") { "Lumi has looked at ${it[1]} of ${it[2]}. You can already search those." },
    rule("Falta leer el texto de (.+)\\. Buscar por cosas, lugares y fechas ya funciona\\.") {
        "Text still has to be read in ${it[1]}. Searching by things, places and dates already works."
    },
    rule("Puedes recuperar (.+)\\. Toca para ver cómo\\.") { "You can free up ${it[1]}. Tap to see how." },
    rule("Puedes recuperar (.+)") { "You can free up ${it[1]}" },
    rule("Todo copiado en (.+)") { "Everything backed up to ${it[1]}" },
    rule("Mirando qué hay en cada foto: (\\d+) de (\\d+)") { "Looking at each photo: ${it[1]} of ${it[2]}" },
    rule("Leyendo el texto de las fotos: faltan (\\d+)") { "Reading text in photos: ${it[1]} to go" },
    rule("(Fotos|Vídeos|Capturas) (\\d.*)") { "${translate(it[1])} ${it[2]}" },
    rule("(.+) libres de (.+)") { "${it[1]} free of ${it[2]}" },
    rule("Restaurar (\\d+)") { "Restore ${it[1]}" },
    rule("Borrar (\\d+)") { "Delete ${it[1]}" },
    rule("(\\d+) días") { "${it[1]} days" },
    rule("De (\\d.*) a (\\d.*)") { "From ${it[1]} to ${it[2]}" },
    rule("El recorte dura (.+) de (.+)") { "The clip lasts ${it[1]} of ${it[2]}" },
    rule("Brillo (\\d+) %") { "Brightness ${it[1]}%" },
    rule("Volumen (\\d+) %") { "Volume ${it[1]}%" },
    rule("Pila de (\\d+) parecidas") { "Stack of ${it[1]} similar" },
    rule("Velocidad (.+)×") { "Speed ${it[1]}×" },
    rule("Cerca de (.+)") { "Near ${it[1]}" },
    rule("Conservar las (\\d+)") { "Keep all ${it[1]}" },
    rule("Ahora pesa (.+)\\. Se guarda una copia más ligera; el original sigue ahí hasta que tú lo borres\\.") {
        "It is ${it[1]} now. A lighter copy is saved; the original stays until you delete it."
    },
    rule("Convirtiendo… (\\d+) %\\. No salgas de esta pantalla hasta que termine\\.") { "Converting… ${it[1]}%. Stay on this screen until it finishes." },
    rule("unos (.+)") { "about ${it[1]}" },
    rule("Guardar GIF · unos (.+)") { "Save GIF · about ${it[1]}" },
    rule("Pegar (\\d+) aquí") { "Paste ${it[1]} here" },
    rule("Para borrar: (.+)") { "To delete: ${translate(it[1])}" },
    rule("Quedan (\\d+)") { "${it[1]} left" },
    rule("Copiando a la tarjeta: (\\d+) de (\\d+)") { "Copying to the card: ${it[1]} of ${it[2]}" },
    rule("Volumen (\\d+) %") { "Volume ${it[1]}%" },
    rule("Sigues en (.+) · Desde el principio") { "Resuming at ${it[1]} · Start over" },
    rule("Subtítulos ([+−-]?[\\d.,]+) s") { "Subtitles ${it[1]} s" },
    // "Agosto de 2025" o "mayo de 2025": una sola palabra, el mes, delante del año. Va la última
    // para no confundirse con frases como "12 de 2000".
    rule("(\\p{L}+) de (\\d{4})") {
        val month = it[1].replaceFirstChar(Char::uppercase)
        "${EN[month] ?: it[1]} ${it[2]}"
    },
    rule("(\\d+) de (\\d+) exportadas a «(.+)»") { "${it[1]} of ${it[2]} exported to “${it[3]}”" },
    rule("Filtro «(.+)» borrado") { "Filter “${it[1]}” deleted" },
    rule("Arrastra las (\\d+) a otra app") { "Drag the ${it[1]} to another app" },
    rule("(.+) → unos (.+)") { "${it[1]} → about ${it[2]}" },
    rule("(.+…) (\\d+) %") { "${translate(it[1])} ${it[2]}%" },
)

/** Textos fijos. La clave es el texto en español tal como está en el código. */
private val EN: Map<String, String> = hashMapOf(
    // Fechas, cantidades y palabras sueltas
    "Hoy" to "Today", "Ayer" to "Yesterday", "hoy" to "today", "ayer" to "yesterday", "Mañana" to "Tomorrow",
    "Año" to "Year", "Mes" to "Month", "Día" to "Day",
    "Enero" to "January", "Febrero" to "February", "Marzo" to "March", "Abril" to "April", "Mayo" to "May", "Junio" to "June",
    "Julio" to "July", "Agosto" to "August", "Septiembre" to "September", "Octubre" to "October", "Noviembre" to "November", "Diciembre" to "December",
    "foto" to "photo", "fotos" to "photos", "elemento" to "item", "elementos" to "items", "resultado" to "result", "resultados" to "results",
    "archivo" to "file", "archivos" to "files", "carpeta" to "folder", "carpetas" to "folders", "elegida" to "chosen", "elegidas" to "chosen", "seleccionada" to "selected", "seleccionadas" to "selected",
    "página" to "page", "páginas" to "pages", "copiada" to "copied", "copiadas" to "copied", "movida" to "moved", "movidas" to "moved",
    "devuelta" to "returned", "devueltas" to "returned", "archivo copiado" to "file copied", "archivos copiados" to "files copied",
    "enviada a la papelera" to "sent to the trash", "enviadas a la papelera" to "sent to the trash",
    "foto de estos días" to "photo from these days", "fotos de estos días" to "photos from these days",
    "foto parecida" to "similar photo", "fotos parecidas" to "similar photos", "oculto" to "hidden", "vacía" to "empty", "Vacía" to "Empty",

    // Navegación y acciones comunes
    "Fotos" to "Photos", "Álbumes" to "Albums", "Buscar" to "Search", "Ajustes" to "Settings", "Volver" to "Back", "Guardar" to "Save",
    "Cancelar" to "Cancel", "Aceptar" to "OK", "Cerrar" to "Close", "Borrar" to "Delete", "Enviar" to "Share", "Editar" to "Edit", "Más" to "More",
    "Copiar" to "Copy", "Quitar" to "Remove", "Crear" to "Create", "Poner" to "Add", "Deshacer" to "Undo", "Ordenar" to "Sort", "Favorita" to "Favorite",
    "Favorita ✓" to "Favorite ✓", "Álbum" to "Album", "Privada" to "Private", "Listo" to "Done", "Comparar" to "Compare", "Nombre" to "Name",
    "Tamaño" to "Size", "Todo" to "All", "Vídeos" to "Videos", "Capturas" to "Screenshots", "Favoritas" to "Favorites", "Con texto" to "With text",
    "Más recientes" to "Newest", "Más antiguas" to "Oldest", "Cantidad de fotos" to "Number of photos",
    "Cámara" to "Camera", "Descargas" to "Downloads", "Vídeos de WhatsApp" to "WhatsApp videos", "Sin carpeta" to "No folder",

    // Bienvenida, permiso y bloqueo
    "Tus fotos se quedan en tu teléfono" to "Your photos stay on your phone",
    "Lumi necesita verlas para enseñártelas, ordenarlas y dejarte buscarlas. Nada más." to "Lumi needs to see them to show, sort and search them for you. Nothing else.",
    "Sin permiso de internet: nada sale de aquí" to "No internet permission: nothing leaves this phone",
    "Sin cuenta, sin anuncios y sin suscripción" to "No account, no ads and no subscription",
    "Candado con huella o PIN, si lo quieres" to "Fingerprint or PIN lock, if you want it",
    "Dar acceso a mis fotos" to "Give access to my photos",
    "Si ya lo rechazaste, ábrelo desde los ajustes" to "If you already said no, open it from settings",
    "Lumi está bloqueada" to "Lumi is locked",
    "Usa tu huella o el bloqueo del teléfono para ver tus fotos." to "Use your fingerprint or your phone lock to see your photos.",
    "Desbloquear" to "Unlock", "Usa tu huella o tu cara" to "Use your fingerprint or face",
    "Usa tu huella, tu cara o el bloqueo del teléfono" to "Use your fingerprint, face or phone lock", "Usar el PIN" to "Use PIN",
    "Bloqueo del teléfono" to "Phone lock", "PIN propio de Lumi" to "Lumi's own PIN", "Ese no es el PIN" to "That is not the PIN",
    "PIN guardado" to "PIN saved", "No coinciden. Empieza otra vez." to "They don't match. Start again.",
    "Escribe tu PIN" to "Enter your PIN", "Elige un PIN" to "Choose a PIN", "Escríbelo otra vez" to "Enter it again",
    "El PIN de Lumi, no el del teléfono" to "Lumi's PIN, not your phone's", "De 4 a 8 cifras" to "4 to 8 digits", "Huella" to "Fingerprint",
    "Pon un bloqueo de pantalla en el teléfono, o usa un PIN propio de Lumi desde Ajustes" to "Set a screen lock on your phone, or use Lumi's own PIN from Settings",
    "Para bloquear álbumes, pon un bloqueo en el teléfono o crea un PIN de Lumi en Ajustes" to "To lock albums, set a lock on your phone or create a Lumi PIN in Settings",

    // Pantalla Fotos
    "Aún no hay fotos" to "No photos yet", "Las fotos y los vídeos de tu teléfono aparecerán aquí." to "Your phone's photos and videos will show up here.",
    "Nada con este filtro" to "Nothing with this filter", "Toca «Todo» para volver a ver la biblioteca completa." to "Tap “All” to see the whole library again.",
    "Aquí solo se pueden elegir fotos" to "Only photos can be picked here", "Aquí solo se pueden elegir vídeos" to "Only videos can be picked here",
    "Elige fotos" to "Pick photos", "Elige una foto" to "Pick a photo", "Hacer una foto" to "Take a photo",
    "Lumi solo ve las fotos que elegiste." to "Lumi only sees the photos you chose.", "Elegir más" to "Choose more", "Ver todas" to "See all",
    "Toca las fotos que quieras enviar" to "Tap the photos you want to send", "Toca una foto para elegirla" to "Tap a photo to pick it",
    "Hace un año" to "A year ago", "Mes anterior" to "Previous month", "Mes siguiente" to "Next month", "Viaje" to "Trip",
    "No se encontró una app de cámara" to "No camera app found", "Este teléfono no permite ventanas flotantes" to "This phone does not allow floating windows",

    // Selección
    "Mover a" to "Move to", "Marcar como favoritas" to "Add to favorites", "Copiar a un álbum" to "Copy to an album",
    "Comparar dos fotos" to "Compare two photos", "Elige exactamente dos fotos para compararlas" to "Pick exactly two photos to compare them",
    "Juntar en un PDF" to "Combine into a PDF", "Elige al menos una foto para el PDF" to "Pick at least one photo for the PDF",
    "Un PDF admite hasta 40 fotos" to "A PDF takes up to 40 photos", "Hacer un collage" to "Make a collage",
    "Elige entre 2 y 6 fotos para el collage" to "Pick between 2 and 6 photos for the collage", "Mover a…" to "Move to…", "Copiar a…" to "Copy to…",
    "No se pudo copiar" to "Could not copy", "No se pudo mover" to "Could not move", "No se pudo guardar" to "Could not save", "No se pudo abrir" to "Could not open",

    // Álbumes
    "Nuevo álbum" to "New album", "Álbum nuevo" to "New album", "Con tu huella" to "With your fingerprint", "Tus carpetas" to "Your folders",
    "Mantén pulsada una para fijarla arriba, bloquearla u ocultarla." to "Press and hold one to pin, lock or hide it.",
    "Con candado" to "Locked", "Hechos por Lumi" to "Made by Lumi", "Bloqueado" to "Locked",
    "Toca y pon la contraseña para verlo" to "Tap and unlock to see it",
    "Después eliges qué fotos van dentro. Cuando exista, mantenlo pulsado para bloquearlo." to "Next you choose which photos go inside. Once it exists, press and hold it to lock it.",
    "Elegir fotos" to "Choose photos", "Toca las fotos que van en este álbum" to "Tap the photos that go in this album",
    "Este álbum está vacío" to "This album is empty", "Sus fotos se han movido o borrado." to "Its photos were moved or deleted.",
    "Opciones del álbum" to "Album options", "Poner candado" to "Lock", "Quitar el candado" to "Remove the lock", "Bloquear con candado" to "Lock",
    "Dejar de fijar" to "Unpin", "Fijar arriba" to "Pin to top", "Dejar de ocultar" to "Unhide", "Ocultar álbum" to "Hide album",
    "Cambiar el nombre" to "Rename", "Android no deja cambiar el nombre de esta carpeta" to "Android does not allow renaming this folder",
    "Borrar el álbum" to "Delete album", "Álbum oculto. Se puede volver a ver desde Ajustes." to "Album hidden. You can show it again from Settings.",
    "Álbum bloqueado" to "Album locked", "Candado quitado" to "Lock removed", "Portada del álbum cambiada" to "Album cover changed",
    "Aún no tienes favoritas" to "No favorites yet", "Toca el corazón al ver una foto y la tendrás siempre aquí." to "Tap the heart on a photo and it will always be here.",
    "Aquí ya no hay fotos" to "No photos here any more", "Se han movido o borrado." to "They were moved or deleted.",
    "Comida" to "Food", "Mascotas" to "Pets", "Playa y mar" to "Beach and sea", "Montaña y nieve" to "Mountains and snow", "Naturaleza" to "Nature",
    "Atardeceres" to "Sunsets", "Ciudad" to "City", "Gente" to "People", "Coches y motos" to "Cars and bikes", "Celebraciones" to "Celebrations", "Papeles" to "Papers",

    // Buscador
    "Nombre, álbum o texto de la foto" to "Name, album or text in the photo", "Nada con estos filtros" to "Nothing with these filters",
    "Prueba con una sola palabra, o usa los filtros de arriba." to "Try a single word, or use the filters above.",
    "Prueba a quitar algún filtro de arriba." to "Try removing one of the filters above.", "Quizá querías decir" to "Did you mean",
    "Cuándo" to "When", "Dónde" to "Where", "Qué hay" to "What's in it", "Recientes" to "Recent", "Lugares" to "Places", "Cosas" to "Things",
    "Toca los filtros de arriba y combínalos. Si prefieres escribir, vale el nombre de un álbum o de un archivo y cualquier texto que aparezca en la foto." to
        "Tap the filters above and combine them. If you prefer to type, an album or file name works, and so does any text that appears in a photo.",

    // Visor y reproductor
    "Reproducir" to "Play", "Velocidad 1×" to "Speed 1×", "Sin sonido" to "Muted", "Con sonido" to "Sound on", "Repetir" to "Repeat",
    "Fotograma" to "Save frame", "Girar" to "Rotate", "Flotante" to "Pop-out", "Bloquear toques" to "Lock screen",
    "Pantalla bloqueada. Mantén pulsado para desbloquear." to "Screen locked. Press and hold to unlock.",
    "Texto de la foto" to "Text in the photo", "Copiar todo" to "Copy all", "Texto copiado" to "Text copied", "Detalles" to "Details",
    "Fecha" to "Date", "Archivo" to "File", "Resolución" to "Resolution", "Duración" to "Duration", "Carpeta" to "Folder",
    "Guardada en" to "Stored on", "Tarjeta de memoria" to "Memory card", "Memoria del teléfono" to "Phone storage", "Lugar" to "Place",
    "Lumi ve" to "Lumi sees", "Disparo" to "Shutter", "Flash" to "Flash", "Disparado" to "Fired",
    "Presentación" to "Slideshow", "Pasa las fotos solas cada tres segundos; un toque la detiene" to "Moves to the next photo every three seconds; a tap stops it",
    "Dibujar o escribir encima" to "Draw or write on it", "Se guarda en una copia" to "Saved as a copy",
    "Copiar el texto de la foto" to "Copy the text in the photo", "Lee lo que hay escrito para pegarlo donde quieras" to "Reads what is written so you can paste it anywhere",
    "Quitar el fondo" to "Remove background", "Deja solo a la persona u objeto principal" to "Keeps only the main person or object",
    "Reducir el peso" to "Reduce file size", "Guarda una copia que ocupa menos; el original no se toca" to "Saves a copy that takes less space; the original is untouched",
    "Usar como portada del álbum" to "Use as album cover", "Enviar sin ubicación" to "Share without location",
    "Se manda una copia sin el lugar donde se hizo" to "Sends a copy without the place where it was taken", "Usar como…" to "Use as…", "Usar como" to "Use as",
    "Fondo de pantalla, foto de contacto y otros" to "Wallpaper, contact photo and more", "Mover a un álbum" to "Move to an album",
    "Mover a la carpeta privada" to "Move to the private folder", "Se guarda cifrada y desaparece de la galería" to "Stored encrypted and removed from the gallery",
    "Leyendo el texto…" to "Reading the text…", "No se ve texto en esta foto" to "No text found in this photo",
    "Nombre cambiado" to "Renamed", "No se pudo cambiar el nombre" to "Could not rename",
    "Fotograma guardado como foto" to "Frame saved as a photo", "No se pudo sacar el fotograma" to "Could not grab the frame",
    "En la tarjeta de memoria" to "On the memory card",
    "Pila" to "Stack", "Mejor toma" to "Best shot", "Elegida por nitidez. Toca otra si prefieres quedarte con ella." to "Picked for sharpness. Tap another one if you would rather keep it.",
    "Has elegido otra toma. Las demás irán a la papelera, donde siguen 30 días." to "You picked another shot. The rest go to the trash, where they stay 30 days.",
    "Quedarme con la mejor" to "Keep the best", "Quedarme con esta" to "Keep this one",

    // Vídeos más ligeros
    "Alta" to "High", "Media" to "Medium", "Ligera" to "Light", "1080p. En el móvil se ve casi igual" to "1080p. Looks almost the same on a phone",
    "720p. Buena para enviar" to "720p. Good for sharing", "480p. La que menos ocupa" to "480p. The smallest",
    "Este vídeo ya ocupa poco: convertirlo no ahorraría espacio." to "This video is already small: converting it would not save space.",
    "Un vídeo largo puede tardar varios minutos y calentar el teléfono." to "A long video can take several minutes and warm up the phone.",
    "Guardar una copia más ligera" to "Save a lighter copy",
    "Copia más ligera guardada. El original sigue en su sitio." to "Lighter copy saved. The original is still where it was.",
    "Este vídeo no se deja convertir" to "This video cannot be converted",

    // Editor y herramientas
    "Libre" to "Free", "No hay memoria suficiente para esta foto" to "Not enough memory for this photo", "Guardando…" to "Saving…",
    "Guardar una copia" to "Save a copy", "Reemplazar la original" to "Replace the original", "No se puede editar esta foto" to "This photo cannot be edited",
    "El formato no se deja abrir." to "The format cannot be opened.", "Antes" to "Before", "Después" to "After", "Enderezar" to "Straighten",
    "Girar 90°" to "Rotate 90°", "Espejo" to "Mirror", "Brillo" to "Brightness", "Contraste" to "Contrast", "Color" to "Color", "Calidez" to "Warmth",
    "Viñeta" to "Vignette", "Desvanecer" to "Fade", "Tono" to "Hue", "Recortar" to "Crop", "Luz y color" to "Light and color", "Filtros" to "Filters",
    "Efectos" to "Effects", "Antes y después" to "Before and after", "Deshacer todo" to "Reset all", "Vívido" to "Vivid", "Cálido" to "Warm",
    "Frío" to "Cool", "Suave" to "Soft", "Blanco y negro" to "Black and white",
    "Foto original reemplazada" to "Original photo replaced", "Copia guardada junto a la original" to "Copy saved next to the original",
    "Pellizca en cualquiera: las dos se mueven juntas" to "Pinch on either one: both move together", "Borrar esta" to "Delete this one",
    "Transparente" to "Transparent", "Blanco" to "White", "Negro" to "Black",
    "Google Play está descargando el recortador. Con conexión a internet tarda alrededor de un minuto; vuelve a intentarlo después." to
        "Google Play is downloading the cut-out tool. With an internet connection it takes about a minute; try again afterwards.",
    "No se pudo separar nada del fondo en esta foto." to "Nothing could be separated from the background in this photo.",
    "Separando del fondo…" to "Separating from the background…", "Recorte guardado en el álbum Lumi" to "Cut-out saved in the Lumi album",
    "Collage guardado en el álbum Lumi" to "Collage saved in the Lumi album", "No hay memoria suficiente para este collage" to "Not enough memory for this collage",
    "Separación" to "Spacing", "Fondo oscuro" to "Dark background", "Dibujar" to "Draw", "Guardar copia" to "Save copy",
    "Copia guardada con tus dibujos" to "Copy saved with your drawings", "No se puede abrir esta foto" to "This photo cannot be opened",
    "El formato no se deja editar." to "The format cannot be edited.", "Texto" to "Text", "Fino" to "Thin", "Medio" to "Medium", "Grueso" to "Thick",
    "Arrastra para colocar el texto. Toca «Texto» para añadir otro." to "Drag to place the text. Tap “Text” to add another.",
    "Escribe el texto" to "Type the text", "Este vídeo es demasiado corto para recortarlo" to "This video is too short to trim",
    "Recortar vídeo" to "Trim video", "Guardar recorte" to "Save clip", "Recortando el vídeo…" to "Trimming the video…",
    "Recorte guardado como vídeo nuevo" to "Clip saved as a new video", "Este vídeo no se deja recortar" to "This video cannot be trimmed",
    "Se guarda como vídeo nuevo, sin perder calidad. El principio puede quedar un instante antes de donde lo marcaste." to
        "Saved as a new video with no quality loss. The start may fall a moment before the point you marked.",
    "No se pudo crear el PDF" to "Could not create the PDF", "PDF guardado en Documentos, carpeta Lumi" to "PDF saved in Documents, Lumi folder",
    "PDF nuevo" to "New PDF", "Toca una página y muévela con las flechas para cambiar el orden." to "Tap a page and move it with the arrows to change the order.",
    "← Antes" to "← Move left", "Después →" to "Move right →", "Hoja A4" to "A4 page", "Tamaño de la foto" to "Photo size", "Creando…" to "Creating…",
    "Guardar y enviar" to "Save and share",

    // Carpeta privada, copia y carpetas ocultas
    "Carpeta privada" to "Private folder", "Aquí no hay nada todavía" to "Nothing here yet",
    "Elige fotos en la galería y usa «Mover a la carpeta privada». Se guardan cifradas y dejan de verse en la galería, la búsqueda y los recuerdos." to
        "Pick photos in the gallery and use “Move to the private folder”. They are stored encrypted and no longer show in the gallery, search or memories.",
    "Mantén pulsada una foto para sacarla de aquí o borrarla. La carpeta se cierra al salir de Lumi." to
        "Press and hold a photo to take it out or delete it. The folder closes when you leave Lumi.",
    "Guardando en la carpeta privada…" to "Saving to the private folder…", "Copia" to "Backup", "Tus fotos en un segundo sitio" to "Your photos in a second place",
    "Destino" to "Destination", "Sin elegir" to "Not set",
    "Puede ser una tarjeta SD, una memoria USB conectada al teléfono o cualquier carpeta. Para llevarlas al PC, copia a una memoria USB o a una carpeta y pásala por cable." to
        "It can be an SD card, a USB drive plugged into the phone or any folder. To take them to a PC, back up to a USB drive or a folder and transfer it by cable.",
    "Elegir carpeta" to "Choose folder", "Cambiar carpeta" to "Change folder", "Todo está copiado" to "Everything is backed up",
    "Aún no se ha hecho ninguna copia." to "No backup has been made yet.",
    "Se ordenan en carpetas por año y mes dentro de «Lumi». Solo se copia lo nuevo." to "They are sorted into year and month folders inside “Lumi”. Only new files are copied.",
    "Copiando…" to "Copying…", "Copiar ahora" to "Back up now", "Carpeta elegida" to "Folder chosen", "No se pudo preparar la copia" to "Could not prepare the copy",
    "No había nada nuevo que copiar" to "Nothing new to back up",
    "Carpetas ocultas" to "Hidden folders", "Hace falta un permiso especial" to "A special permission is needed",
    "Algunas apps guardan fotos y vídeos en carpetas que Android esconde a las galerías. Para verlas, Lumi necesita el acceso a todos los archivos, que se concede en los ajustes del sistema. Sigue sin salir nada del teléfono." to
        "Some apps keep photos and videos in folders that Android hides from galleries. To see them, Lumi needs access to all files, granted in the system settings. Still nothing leaves the phone.",
    "Abrir los ajustes del permiso" to "Open the permission settings", "Ya lo he concedido" to "I have granted it", "Buscando…" to "Searching…",
    "Lumi está recorriendo las carpetas del teléfono." to "Lumi is going through the phone's folders.", "No hay nada escondido" to "Nothing is hidden",
    "Ninguna carpeta oculta tiene fotos ni vídeos." to "No hidden folder has photos or videos.",
    "Se pueden ver, pero no borrar ni mover desde aquí." to "They can be viewed, but not deleted or moved from here.",

    // Reproductor: GIF, sonido y subtítulos
    "Hacer un GIF" to "Make a GIF", "Hasta 8 segundos. Se ve a 10 fotogramas por segundo y se repite sin parar." to
        "Up to 8 seconds. It plays at 10 frames per second and loops forever.",
    "GIF guardado en el álbum Lumi" to "GIF saved in the Lumi album", "No se pudo hacer el GIF" to "Could not make the GIF",
    "Pequeño" to "Small", "Mediano" to "Medium",
    "Ese archivo no tiene subtítulos que Lumi entienda" to "That file has no subtitles Lumi can read",
    "Sigue sonando con la pantalla apagada. Los controles están en la notificación." to "It keeps playing with the screen off. The controls are in the notification.",
    "Solo sonido" to "Audio only", "Realzar voces" to "Boost voices", "Subtítulos" to "Subtitles", "Otro archivo" to "Another file",
    "Hoy no hay recuerdos de otros años" to "No memories from other years today", "Recuerdos" to "Memories",
    "Quitar de favoritas" to "Remove from favorites", "Atrás 10 segundos" to "Back 10 seconds", "Adelante 10 segundos" to "Forward 10 seconds",
    "Opciones del vídeo" to "Video options", "Reproducción" to "Playback", "Sonido" to "Sound", "Crear" to "Create", "Velocidad" to "Speed",
    "Sí" to "On", "No" to "Off", "Girar la pantalla" to "Rotate screen", "Ventana flotante" to "Pop-out window",
    "Sigue viéndose encima de otras apps" to "Keeps playing on top of other apps", "Bloquear la pantalla" to "Lock the screen",
    "Para que un toque sin querer no lo pare" to "So an accidental tap won't stop it", "Silenciado" to "Muted", "Activado" to "On",
    "Volumen extra" to "Extra volume", "Para vídeos grabados muy bajos" to "For videos recorded too quietly",
    "Se entiende mejor a quien habla" to "Makes speech easier to understand", "Sigue sonando con la pantalla apagada" to "Keeps playing with the screen off",
    "Cargar subtítulos" to "Load subtitles", "Elige un archivo .srt del teléfono" to "Pick an .srt file on your phone", "Mostrar" to "Show",
    "Grande" to "Large", "Sincronizar" to "Sync", "Sin cambios" to "No change", "Guardar fotograma" to "Save frame",
    "El momento que se ve, como foto" to "The moment on screen, as a photo", "Un trozo de hasta 8 segundos" to "A clip of up to 8 seconds",
    // Menú «Más» y fondo de pantalla
    "Foto girada" to "Photo rotated", "Este formato no se puede girar sin perder calidad. Usa Editar." to "This format can't be rotated without losing quality. Use Edit.",
    "Este archivo" to "This file", "Organizar" to "Organize", "Compartir" to "Share", "Poner de fondo" to "Set as wallpaper",
    "Pantalla de inicio, de bloqueo o las dos" to "Home screen, lock screen or both",
    "También manteniendo pulsado el título de arriba" to "Or press and hold the title at the top", "Girar la foto" to "Rotate photo",
    "Un cuarto de vuelta, sin perder calidad" to "A quarter turn, with no quality loss", "Ver en horizontal" to "View in landscape",
    "Volver a vertical" to "Back to portrait", "Gira la pantalla aunque el teléfono esté de pie" to "Rotates the screen even if the phone is upright",
    "Ocultar" to "Hide", "Pasa a la carpeta privada, cifrada, y deja de verse en la galería" to "Moves to the encrypted private folder and disappears from the gallery",
    "Usar en otra app" to "Use in another app", "Foto de contacto y otros usos que ofrezca el teléfono" to "Contact photo and other uses your phone offers",
    "Pantalla de inicio" to "Home screen", "Pantalla de bloqueo" to "Lock screen", "Las dos" to "Both",
    "Fondo de pantalla cambiado" to "Wallpaper changed", "No se pudo poner de fondo" to "Could not set the wallpaper", "Poniendo…" to "Setting…",
    "Arrastra la foto para elegir qué parte se ve" to "Drag the photo to choose which part shows", "Poner en" to "Set on",
    "Vista de inicio" to "Home preview", "Vista de bloqueo" to "Lock preview",
    // Copiar y pegar, accesibilidad, información y documentos
    "Ya están en este álbum" to "They're already in this album", "Android no deja pegar en esta carpeta" to "Android doesn't allow pasting into this folder",
    "Vídeo" to "Video", "Foto" to "Photo", "favorita" to "favorite", "Cortar" to "Cut",
    "Listas para pegar. Abre un álbum y pulsa «Pegar»." to "Ready to paste. Open an album and tap “Paste”.",
    "Información" to "Info", "Fecha, lugar, cámara y lo que Lumi ve en ella" to "Date, place, camera and what Lumi sees in it",
    "Escanear documento" to "Scan document", "Recorta la hoja, la endereza y limpia el fondo, como un escáner" to
        "Crops the page, straightens it and cleans the background, like a scanner",
    "Arrastra las esquinas hasta los bordes de la hoja" to "Drag the corners to the edges of the page", "Elige cómo queda y guárdalo" to "Choose the look and save it",
    "Buscando la hoja…" to "Looking for the page…", "Siguiente" to "Next", "Enderezando…" to "Straightening…",
    "Guardar como foto nueva" to "Save as a new photo", "Documento guardado junto a la foto original" to "Document saved next to the original photo",
    "Gris" to "Gray",
    // Escáner, girar y quitar el fondo
    "No se pudo guardar el documento" to "Could not save the document",
    "Documento guardado en el álbum Documentos y como PDF" to "Document saved in the Documents album and as a PDF",
    "Escáner" to "Scanner", "Documentos" to "Documents", "Cambiar la vista" to "Change view",
    "El escáner aún no está listo: Google Play lo está descargando. Prueba otra vez en un minuto." to
        "The scanner isn't ready yet: Google Play is downloading it. Try again in a minute.",
    "Girar" to "Rotate", "Abriendo la foto…" to "Opening the photo…", "↺ Izquierda" to "↺ Left", "Derecha ↻" to "Right ↻",
    "A la izquierda, a la derecha o en espejo, viendo cómo queda" to "Left, right or mirrored, previewing the result",
    "Haz la foto del papel o elige una; sale enderezado y limpio, también en PDF" to "Take a photo of the paper or pick one; it comes out straight and clean, also as a PDF",
    "Detrás" to "Behind", "Desenfocado" to "Blurred", "Fondo en gris" to "Gray background", "Borde" to "Edge", "Suave" to "Soft",
    "Normal" to "Normal", "Nítido" to "Sharp", "Ajustar al recorte" to "Crop to subject",
    "Recorte guardado junto a la foto original" to "Cut-out saved next to the original photo",
    // Tarjeta SD, orden de álbumes y deshacer
    "Ya están en la tarjeta" to "They're already on the card", "Copiando a la tarjeta…" to "Copying to the card…",
    "No se pudo copiar a la tarjeta" to "Could not copy to the card",
    "Copiadas a la tarjeta. Ahora confirma que se borren del teléfono." to "Copied to the card. Now confirm deleting them from the phone.",
    "Ordenar álbumes" to "Arrange albums", "Mantén pulsado uno y arrástralo a su sitio" to "Press and hold one and drag it into place",
    "Arrastrar" to "Drag", "A mano" to "Custom", "Mover a la tarjeta SD" to "Move to SD card", "Teléfono" to "Phone",
    "Tarjeta SD" to "SD card", "Pasar a la tarjeta" to "Move to the card", "Vídeos de hace más de 6 meses" to "Videos older than 6 months",
    "vídeo" to "video", "vídeos" to "videos", "Fotos de hace más de un año" to "Photos older than a year", "Mover" to "Move",
    "Se copian a la tarjeta y después Android te pide permiso para borrarlas del teléfono. Siguen viéndose igual en Lumi." to
        "They're copied to the card, then Android asks you to allow deleting them from the phone. They still show up the same in Lumi.",
    "Deshecho" to "Undone",
    // Ajustes por grupos
    "Fotos y álbumes" to "Photos and albums", "Privacidad y seguridad" to "Privacy and security", "Almacenamiento" to "Storage",
    "Política de privacidad" to "Privacy policy", "Se abre en el navegador" to "Opens in your browser", "Contacto" to "Contact",
    "Correo copiado" to "Email copied", "parte en la tarjeta" to "partly on the card",
    // Menú «Más», editor, fondo, collage, buscador, historias y repaso rápido
    "Fondo" to "Wallpaper", "Sin fondo" to "Cut out", "Reducir" to "Shrink", "Horizontal" to "Landscape", "Vertical" to "Portrait",
    "Sin ubicación" to "No location", "Copiada. Mantén pulsado en un chat para pegarla." to "Copied. Press and hold in a chat to paste it.",
    "foto ese día" to "photo that day", "fotos ese día" to "photos that day",
    "Encuadre auto" to "Auto frame", "Perspectiva" to "Perspective", "Intensidad" to "Intensity",
    "No se encontró nada principal que encuadrar" to "Nothing stands out enough to frame",
    "Inicio" to "Home", "Bloqueo" to "Lock", "Oscurecer" to "Darken", "Desenfocar" to "Blur",
    "Pellizca para ampliar y arrastra" to "Pinch to zoom and drag", "En las dos" to "On both",
    "Poner en inicio" to "Set on home", "Poner en bloqueo" to "Set on lock",
    "Revista" to "Magazine", "Mosaico" to "Mosaic", "Tira" to "Strip", "Polaroid" to "Polaroid", "Crema" to "Cream", "Noche" to "Night",
    "Bordes" to "Borders", "Esquinas" to "Corners", "Título" to "Title",
    "Toca otra foto para cambiarlas de sitio" to "Tap another photo to swap them", "Toca dos fotos para cambiarlas de sitio" to "Tap two photos to swap them",
    "Cosa" to "Thing", "Escrito en la foto" to "Written in the photo",
    "Repaso rápido" to "Quick review", "Izquierda para borrar, derecha para quedarte con ella" to "Left to delete, right to keep it",
    "Repaso terminado" to "Review finished", "No queda nada por revisar aquí." to "Nothing left to review here.",
    "Pulsa «Borrar» para mandar a la papelera lo que apartaste." to "Tap “Delete” to send what you set aside to the trash.",
    "Nada apartado todavía" to "Nothing set aside yet", "Conservar" to "Keep", "Deslizar" to "Swipe", "WhatsApp" to "WhatsApp",
    // Espacio y papelera
    "Copias exactas" to "Exact copies", "Fotos parecidas" to "Similar photos", "Calendario" to "Calendar",
    "La misma imagen guardada más de una vez. Lumi compara cada copia con la original antes de enseñarla." to
        "The same image saved more than once. Lumi compares each copy with the original before showing it.",
    "Fotos casi iguales hechas seguidas. No son copias: mira cada grupo y quédate con las que quieras." to
        "Nearly identical photos taken in a row. They are not copies: look at each group and keep the ones you want.",
    "Pueden estar movidas o desenfocadas. Míralas antes de quitarlas." to "They may be shaky or out of focus. Look at them before removing them.",
    "No hay copias, fotos parecidas, vídeos grandes ni capturas antiguas que revisar." to "No copies, similar photos, large videos or old screenshots to review.",
    "Para revisar" to "To review", "Nada viene marcado: tú eliges qué quitar. Lo que quites pasa 30 días en la papelera." to
        "Nothing comes pre-selected: you choose what to remove. Whatever you remove stays 30 days in the trash.",
    "Comprobando…" to "Checking…", "Lumi está comparando cada copia con su original." to "Lumi is comparing each copy with its original.",
    "Nada que revisar" to "Nothing to review", "Aquí no queda nada." to "Nothing left here.", "Quitar selección" to "Clear selection",
    "Elegir las copias" to "Select the copies", "Elegir todo" to "Select all", "Toca para elegir. Mantén pulsado para verla en grande." to
        "Tap to select. Press and hold to see it full size.", "Elige lo que quieras quitar" to "Choose what you want to remove",
    "Archivo idéntico" to "Identical file", "Misma imagen" to "Same image", "Se propone conservar" to "Suggested to keep",
    "La más nítida" to "The sharpest", "Has elegido todas las de este grupo: no quedará ninguna." to "You selected every photo in this group: none will be left.",
    "grupo" to "group", "grupos" to "groups", "Cuadrícula" to "Grid", "Lista" to "List", "Con fotos" to "With photos", "Nuevo" to "New",
    "fijado" to "pinned", "Toca un día para ver lo que hiciste o guardaste ese día." to "Tap a day to see what you took or saved that day.",
    "Repetidas" to "Similar photos", "Se conserva la mejor toma de cada pila." to "The best shot of each stack is kept.",
    "Vídeos grandes" to "Large videos", "Vídeos de más de 50 MB, del más pesado al más ligero." to "Videos over 50 MB, heaviest first.",
    "Capturas antiguas" to "Old screenshots", "Capturas de pantalla de hace más de 30 días." to "Screenshots older than 30 days.",
    "Quizá borrosas" to "Maybe blurry", "Pueden estar movidas o desenfocadas. Marca solo las que quieras quitar." to "They may be shaky or out of focus. Mark only the ones you want to remove.",
    "Duplicadas" to "Duplicates", "El mismo archivo guardado más de una vez. De cada grupo se conserva una copia." to "The same file saved more than once. One copy of each group is kept.",
    "Espacio" to "Storage", "Todo en orden" to "All tidy", "No hay repetidas, vídeos grandes ni capturas antiguas que revisar." to "No similar photos, large videos or old screenshots to review.",
    "que puedes recuperar si quieres" to "that you can free up if you want", "Ves todo antes de borrar. Lo que quites pasa 30 días en la papelera." to "You see everything before deleting. What you remove stays 30 days in the trash.",
    "Toca las que quieras quitar" to "Tap the ones you want to remove", "Papelera" to "Trash", "La papelera está vacía" to "The trash is empty",
    "Lo que borres se guarda aquí 30 días por si te arrepientes." to "What you delete is kept here for 30 days in case you change your mind.",
    "Cada elemento se borra solo, para siempre, cuando se cumplen sus 30 días. En rojo, los que se van en tres días o menos." to
        "Each item is deleted for good once its 30 days are up. In red, the ones that go in three days or less.",
    "Restaurar todo" to "Restore all", "Vaciar" to "Empty",

    // Ajustes
    "Buscar un ajuste" to "Search settings", "Aspecto" to "Appearance", "Tema" to "Theme", "Sistema" to "System", "Claro" to "Light", "Oscuro" to "Dark",
    "Lila" to "Lilac", "Coral" to "Coral", "Verde" to "Green", "Azul" to "Blue", "Ámbar" to "Amber", "Negro puro" to "Pure black",
    "Fondo negro del todo en el tema oscuro. Gasta menos batería en pantallas OLED." to "Fully black background in the dark theme. Uses less battery on OLED screens.",
    "Idioma" to "Language", "El del teléfono" to "Same as phone", "Privacidad" to "Privacy", "Pedir huella al abrir Lumi" to "Ask for fingerprint when opening Lumi",
    "Usa tu huella o el bloqueo del teléfono (PIN, patrón o contraseña)." to "Uses your fingerprint or phone lock (PIN, pattern or password).",
    "Cómo se desbloquea" to "How it unlocks", "Con lo que uses en el teléfono: huella, cara, PIN, patrón o contraseña." to "With whatever you use on the phone: fingerprint, face, PIN, pattern or password.",
    "Con un PIN solo para Lumi, distinto del teléfono. La huella sigue valiendo como atajo." to "With a PIN just for Lumi, different from the phone's. Your fingerprint still works as a shortcut.",
    "Cambiar el PIN" to "Change PIN", "Mostrar álbumes ocultos" to "Show hidden albums",
    "Los álbumes que ocultaste vuelven a verse, marcados como ocultos." to "The albums you hid show again, marked as hidden.",
    "Fotos cifradas que solo se abren con tu huella o tu bloqueo" to "Encrypted photos that only open with your fingerprint or lock",
    "Carpetas ocultas del sistema" to "Hidden system folders", "Fotos y vídeos que otras apps guardan donde las galerías no miran" to "Photos and videos other apps keep where galleries do not look",
    "Tus fotos" to "Your photos", "Orden de la pantalla Fotos" to "Order of the Photos screen", "Recientes primero" to "Newest first", "Antiguas primero" to "Oldest first",
    "Liberar espacio" to "Free up space", "Repetidas, vídeos grandes y capturas antiguas" to "Similar photos, large videos and old screenshots",
    "Usar la papelera" to "Use the trash", "Lo que borras se guarda 30 días y después se elimina solo, para siempre." to "What you delete is kept 30 days and then removed for good.",
    "Lo que borras se elimina en el acto y no se puede recuperar." to "What you delete is removed at once and cannot be recovered.",
    "Copia de seguridad" to "Backup", "A tarjeta SD, memoria USB o una carpeta" to "To an SD card, USB drive or folder",
    "Análisis de las fotos" to "Photo analysis", "Sin fotos que analizar" to "No photos to analyze", "Todo analizado" to "All photos analyzed",
    "Sirve para buscar, para los álbumes de cosas y viajes y para detectar repetidas. Se hace en el teléfono, despacio, y se detiene mientras tocas la pantalla." to
        "Used for search, for the albums of things and trips, and to spot similar photos. It runs on your phone, slowly, and pauses while you touch the screen.",
    "Acerca de" to "About", "Sin anuncios, sin cuenta y sin permiso de internet: tus fotos no salen del teléfono." to "No ads, no account and no internet permission: your photos never leave the phone.",
    "Si no está aquí, borra lo escrito para ver todos los ajustes." to "If it is not here, clear what you typed to see every setting.",
    "Toca para revisar repetidas, vídeos grandes y capturas antiguas." to "Tap to review similar photos, large videos and old screenshots.",

    // Séptima tanda: señuelo, filtros, movimiento, importar, tu año, dibujar, vídeo y personas
    "Con flash" to "With flash",
    "Alta resolución" to "High resolution",
    "Menos de 1 MB" to "Under 1 MB",
    "De 1 a 10 MB" to "1 to 10 MB",
    "De 10 a 100 MB" to "10 to 100 MB",
    "Más de 100 MB" to "Over 100 MB",
    "En movimiento" to "Motion",
    "Selfies" to "Selfies",
    "Horizontales" to "Landscape",
    "Verticales" to "Portrait",
    "Formato" to "Format",
    "Quién" to "Who",
    "PIN señuelo" to "Decoy PIN",
    "Puesto" to "Set",
    "Sin poner" to "Not set",
    "Elige el PIN señuelo" to "Choose the decoy PIN",
    "Distinto de tu PIN. Abrirá otra carpeta privada." to "Different from your PIN. It will open another private folder.",
    "Ese es tu PIN señuelo. Elige otro." to "That is your decoy PIN. Choose another one.",
    "Tiene que ser distinto de tu PIN" to "It has to be different from your PIN",
    "PIN señuelo guardado" to "Decoy PIN saved",
    "PIN señuelo quitado" to "Decoy PIN removed",
    "Si alguien te obliga a abrir la carpeta privada, escribe este PIN: se abre otra, con lo que tú hayas guardado en ella." to "If someone forces you to open the private folder, type this PIN: another one opens, with whatever you saved in it.",
    "Cambiar el PIN señuelo" to "Change decoy PIN",
    "Quitar el PIN señuelo" to "Remove decoy PIN",
    "Movimiento" to "Motion",
    "Foto en movimiento" to "Motion photo",
    "Guardar este instante" to "Save this moment",
    "Guardar el vídeo" to "Save the video",
    "Elige el instante y guárdalo como foto" to "Pick the moment and save it as a photo",
    "Para en el instante que quieras" to "Stop at any moment you like",
    "Instante guardado como foto nueva" to "Moment saved as a new photo",
    "No se pudo guardar ese instante" to "That moment could not be saved",
    "Vídeo guardado junto a la foto" to "Video saved next to the photo",
    "No se pudo guardar el vídeo" to "The video could not be saved",
    "Foto en movimiento: guardar el vídeo o un instante" to "Motion photo: save the video or a moment",
    "Importar" to "Import",
    "Importadas" to "Imported",
    "Desde una cámara, una tarjeta o una memoria USB" to "From a camera, a card or a USB drive",
    "Puedes salir de esta pantalla: la copia sigue. No desconectes la cámara." to "You can leave this screen: copying continues. Do not unplug the camera.",
    "archivo no se pudo copiar" to "file could not be copied",
    "archivos no se pudieron copiar" to "files could not be copied",
    "Ya están en el teléfono. Lo que hay en la cámara no se ha tocado." to "They are on your phone now. Nothing on the camera was touched.",
    "Ver el álbum" to "See the album",
    "Importar de otro sitio" to "Import from somewhere else",
    "Buscando fotos y vídeos…" to "Looking for photos and videos…",
    "Conecta lo que quieras importar" to "Connect what you want to import",
    "Cámara: conéctala con su cable y elige en ella el modo PTP o MTP (a veces se llama «PC» o «transferencia»)." to "Camera: connect it with its cable and choose PTP or MTP mode on it (sometimes called “PC” or “transfer”).",
    "Tarjeta o memoria USB: conéctala con un lector o un adaptador USB-C." to "Card or USB drive: connect it with a reader or a USB-C adapter.",
    "Pulsa el botón y elige la cámara o la memoria. En las cámaras las fotos suelen estar en la carpeta DCIM." to "Tap the button and choose the camera or drive. On cameras, photos are usually in the DCIM folder.",
    "Elegir de dónde importar" to "Choose where to import from",
    "Lumi solo copia: nunca borra nada de la cámara ni de la memoria." to "Lumi only copies: it never deletes anything from the camera or drive.",
    "Todo lo nuevo" to "All new",
    "Ninguna" to "None",
    "ya la tienes" to "already on phone",
    "ya las tienes" to "already on phone",
    "Ya la tienes" to "Already on phone",
    "Elige qué importar" to "Choose what to import",
    "nueva" to "new",
    "nuevas" to "new",
    "encontrado" to "found",
    "encontrados" to "found",
    "foto importada" to "photo imported",
    "fotos importadas" to "photos imported",
    "Importar de una cámara o memoria" to "Import from a camera or drive",
    "Copia lo nuevo de una cámara, una tarjeta o una memoria USB, sin duplicar" to "Copies what is new from a camera, card or USB drive, without duplicates",
    "Tu año en fotos" to "Your year in photos",
    "No hay fotos de ese año, sin contar capturas de pantalla." to "No photos from that year, not counting screenshots.",
    "Ver lo mejor del año" to "See the best of the year",
    "Tu año, día a día" to "Your year, day by day",
    "Cada cuadro es un día; cuanto más claro, más fotos. Toca uno para verlas." to "Each square is a day; the brighter, the more photos. Tap one to see them.",
    "Dónde estuviste" to "Where you were",
    "Lo que más fotografiaste" to "What you photographed most",
    "Con qué las hiciste" to "What you shot them with",
    "Mes a mes" to "Month by month",
    "tu mes con más fotos" to "your month with the most photos",
    "tu día con más fotos" to "your day with the most photos",
    "viaje" to "trip",
    "viajes" to "trips",
    "favoritas" to "favorites",
    "Pincel" to "Brush",
    "Rotulador" to "Highlighter",
    "Flecha" to "Arrow",
    "Línea" to "Line",
    "Círculo" to "Circle",
    "Rectángulo" to "Rectangle",
    "Pegatina" to "Sticker",
    "Pegatinas" to "Stickers",
    "Sencillo" to "Plain",
    "Con fondo" to "Boxed",
    "Contorno" to "Outline",
    "Titular" to "Headline",
    "Clásica" to "Classic",
    "Máquina" to "Typewriter",
    "Grosor" to "Thickness",
    "Rehacer" to "Redo",
    "Toca algo para moverlo. Con dos dedos se agranda y se gira." to "Tap something to move it. Use two fingers to resize and rotate it.",
    "Arrastra para moverlo; con dos dedos, agrándalo o gíralo." to "Drag to move it; with two fingers, resize or rotate it.",
    "Con el color elegido. Después se mueve, se agranda y se gira." to "In the chosen color. You can move, resize and rotate it afterwards.",
    "Editar vídeo" to "Edit video",
    "Guardar vídeo" to "Save video",
    "Encuadre" to "Framing",
    "Original" to "Original",
    "Vivo" to "Vivid",
    "Sepia" to "Sepia",
    "Desvaído" to "Faded",
    "Drama" to "Drama",
    "Luz" to "Light",
    "Velocidad normal" to "Normal speed",
    "Con sonido" to "With sound",
    "Sin sonido" to "No sound",
    "El sonido se ajusta a la velocidad sin volverse agudo ni grave." to "The sound follows the speed without getting higher or lower.",
    "El encuadre recorta por el centro para llenar la forma elegida." to "Framing crops from the center to fill the chosen shape.",
    "El vídeo nuevo se guarda sin pista de sonido." to "The new video is saved without a sound track.",
    "Vídeo nuevo guardado junto al original" to "New video saved next to the original",
    "Este vídeo no se pudo editar" to "This video could not be edited",
    "Personas" to "People",
    "Ver todos" to "See all",
    "Añadir nombre" to "Add name",
    "persona" to "person",
    "personas" to "people",
    "Sin nombre" to "No name",
    "Ponerle nombre" to "Add a name",
    "Opciones" to "Options",
    "Fotos con otra persona" to "Photos with someone else",
    "Ocultar a esta persona" to "Hide this person",
    "Con quién" to "With whom",
    "Ninguna juntos" to "None together",
    "Agrupar caras está apagado" to "Face grouping is off",
    "Actívalo en Ajustes, en «Análisis de las fotos». Se hace en el teléfono y nada sale de él." to "Turn it on in Settings, under “Photo analysis”. It runs on your phone and nothing leaves it.",
    "Aún no hay personas" to "No people yet",
    "Buscando caras…" to "Finding faces…",
    "Lumi junta las caras que se repiten en al menos tres fotos. Se hace en el teléfono, despacio, y se detiene mientras lo usas." to "Lumi groups faces that appear in at least three photos. It runs on your phone, slowly, and pauses while you use it.",
    "Ponles nombre para buscarlas escribiéndolo. Si alguien sale dos veces, dale el mismo nombre a las dos y se juntan." to "Name them to find them by typing. If someone shows up twice, give both the same name and they merge.",
    "No quedan fotos" to "No photos left",
    "¿Quién es?" to "Who is it?",
    "¿Es la misma que…?" to "Is it the same as…?",
    "Agrupar caras" to "Group faces",
    "Personas ocultas" to "Hidden people",
    "persona oculta" to "hidden person",
    "personas ocultas" to "hidden people",
    "Apagado. Lo que se sabía de las caras está borrado." to "Off. Everything known about faces has been deleted.",
    "Junta las fotos de cada persona. En el teléfono: ninguna cara sale de él." to "Groups each person's photos. On your phone: no face ever leaves it.",
    "Persona oculta. Puedes volver a verla desde Ajustes." to "Person hidden. You can show them again from Settings.",

    // Octava tanda
    "Abajo a la derecha" to "Bottom right",
    "Abajo a la izquierda" to "Bottom left",
    "En el centro" to "Center",
    "Rápido" to "Fast",
    "Tranquilo" to "Calm",
    "Lento" to "Slow",
    "Conversaciones" to "Conversations",
    "Compras y recibos" to "Shopping and receipts",
    "Mapas y direcciones" to "Maps and directions",
    "Entradas y reservas" to "Tickets and bookings",
    "Redes sociales" to "Social media",
    "Memes e imágenes" to "Memes and images",
    "Otras" to "Other",
    "tarjeta de embarque" to "boarding pass",
    "codigo de reserva" to "booking code",
    "escribe un mensaje" to "type a message",
    "Ojos cerrados" to "Eyes closed",
    "Fotos en las que alguien parpadea. Puede que haya otra igual con los ojos abiertos." to "Photos where someone is blinking. There may be another one just like it with eyes open.",
    "No se pudo crear el GIF" to "The GIF could not be made",
    "No se pudo exportar" to "Could not export",
    "GIF guardado en el álbum Lumi" to "GIF saved to the Lumi album",
    "Vídeo guardado en el álbum Lumi" to "Video saved to the Lumi album",
    "No se pudo montar el vídeo" to "The video could not be made",
    "Exportar: tamaño, formato, marca de agua…" to "Export: size, format, watermark…",
    "Elige alguna foto para exportar" to "Pick some photos to export",
    "Vídeo con música" to "Video with music",
    "Elige al menos dos fotos para el vídeo" to "Pick at least two photos for the video",
    "Animar (GIF)" to "Animate (GIF)",
    "Elige entre 2 y 40 fotos para animarlas" to "Pick between 2 and 40 photos to animate them",
    "Animar" to "Animate",
    "Creando el GIF…" to "Making the GIF…",
    "Ida y vuelta" to "Back and forth",
    "Grande (720 px)" to "Large (720 px)",
    "Ligero (480 px)" to "Light (480 px)",
    "Guardar GIF" to "Save GIF",
    "Exportar" to "Export",
    "Exportando…" to "Exporting…",
    "Tamaño (lado largo)" to "Size (long side)",
    "Calidad" to "Quality",
    "Ligera" to "Light",
    "Buena" to "Good",
    "Máxima" to "Maximum",
    "Marca de agua" to "Watermark",
    "Tu nombre o tu marca (opcional)" to "Your name or brand (optional)",
    "Datos de la foto" to "Photo details",
    "Quitar ubicación" to "Remove location",
    "Quitar datos de cámara" to "Remove camera details",
    "Guardar en «Lumi Exportadas»" to "Save to “Lumi Exportadas”",
    "Y compartir" to "And share",
    "Las originales no se tocan. Las copias van al álbum «Lumi Exportadas»." to "The originals are not touched. The copies go to the “Lumi Exportadas” album.",
    "foto exportada" to "photo exported",
    "fotos exportadas" to "photos exported",
    "Vídeo de recuerdos" to "Memory video",
    "Aquí no hay fotos para hacer un vídeo" to "There are no photos here to make a video",
    "Canción elegida" to "Chosen song",
    "♪ Elegir canción" to "♪ Choose song",
    "♪ Cambiar canción" to "♪ Change song",
    "Sin música" to "No music",
    "Montando el vídeo…" to "Making the video…",
    "Crear vídeo" to "Create video",
    "Título" to "Title",
    "Se guarda en el álbum «Lumi». La canción es un archivo de tu teléfono." to "It is saved to the “Lumi” album. The song is a file on your phone.",
    "Capturas" to "Screenshots",
    "No hay capturas" to "No screenshots",
    "Las capturas de pantalla aparecerán aquí, ordenadas por tipo." to "Screenshots will show up here, sorted by type.",
    "Lumi aún está leyendo el texto de algunas fotos: el orden mejorará cuando termine." to "Lumi is still reading the text of some photos: sorting will improve when it finishes.",
    "captura ordenada" to "sorted screenshot",
    "capturas ordenadas" to "sorted screenshots",
    "Capturas ordenadas" to "Sorted screenshots",
    "Chats, compras, mapas…" to "Chats, shopping, maps…",
    "Retrato" to "Portrait",
    "Retrato guardado junto a la foto original" to "Portrait saved next to the original photo",
    "Buscando a quién enfocar…" to "Finding who to focus on…",
    "Fondo en blanco y negro" to "Black and white background",
    "Oscurecer el fondo" to "Darken background",
    "Mantén el dedo en la foto para ver la original." to "Hold your finger on the photo to see the original.",
    "Desenfoque" to "Blur",
    "Arrastra la foto a otra app" to "Drag the photo to another app",
    "Guardar mis ajustes como filtro" to "Save my settings as a filter",
    "Arrastra la línea para cambiarla; toca dos veces un punto para quitarlo." to "Drag the line to change it; double-tap a point to remove it.",
    "Saturación" to "Saturation",
    "Quitar ruido" to "Reduce noise",
    "Nombre del filtro" to "Filter name",
    "Mi filtro" to "My filter",
    "Filtro guardado. Lo tienes en «Filtros» para cualquier foto." to "Filter saved. You'll find it in “Filters” for any photo.",
    "Curvas" to "Curves",
    "Tonos" to "Tones",
    "Detalle" to "Detail",
    "Todo" to "All",
    "Rojo" to "Red",
    "Verde" to "Green",
    "Azul" to "Blue",
    "Rojos" to "Reds",
    "Naranjas" to "Oranges",
    "Amarillos" to "Yellows",
    "Verdes" to "Greens",
    "Turquesas" to "Aquas",
    "Azules" to "Blues",
    "Morados" to "Purples",
    "Rosas" to "Pinks",
    "Luminosidad" to "Luminance",
    "Nitidez" to "Sharpness",
    "Grano" to "Grain",
    "Sombras" to "Shadows",
    "Luces" to "Highlights",
    "No se pudo hacer la larga exposición" to "The long exposure could not be made",
    "Estela de luces" to "Light trails",
    "Larga exposición" to "Long exposure",
    "Lo más claro de cada instante: las luces que se mueven dejan su rastro." to "The brightest of every moment: moving lights leave a trail.",
    "Los fotogramas superpuestos: el agua y lo que se mueve se vuelven seda." to "Frames layered together: water and anything moving turns silky.",
    "Guardar como foto" to "Save as photo",
    "Guardada como foto nueva" to "Saved as a new photo",
    "Calculando…" to "Working…",
    "Volver" to "Back",
    "Destacar la mejor foto de cada día" to "Highlight the best photo of each day",
    "En la vista por días, la más bonita de cada día sale en grande: favorita, nítida, con gente sonriendo." to "In the day view, the nicest photo of each day is shown large: a favorite, sharp, with people smiling.",
    "Toca o arrastra sobre el texto para elegir un trozo" to "Tap or drag over the text to pick a part",
    "línea elegida" to "line chosen",
    "líneas elegidas" to "lines chosen",
    "Texto copiado" to "Text copied",
    "Modo retrato: desenfocar el fondo" to "Portrait mode: blur the background",
    "Más como esta" to "More like this",
    "Este día, otros años" to "This day, other years",
    "Elegida por nitidez y, si sale gente, con todos los ojos abiertos. Toca otra si prefieres quedarte con ella." to "Chosen for sharpness and, if there are people, with everyone's eyes open. Tap another if you'd rather keep that one.",
    "Hacer un vídeo con música" to "Make a video with music",
)
