package com.lumi.galeria

/** Traducciones de las funciones nuevas (notas, álbumes inteligentes, pegatinas, editores, consejos…). Se suman a [EN] en English.kt. */
internal val EN_MORE: Map<String, String> = hashMapOf(
    // Catálogo «Descubre Lumi»
    "Y además" to "And also",
    "Busca por lo que se ve" to "Search by what you see",
    "Escribe «playa», «perro» o «tickets»: Lumi sabe qué sale en cada foto, sin conexión." to "Type “beach”, “dog” or “receipts”: Lumi knows what is in every photo, offline.",
    "Busca el texto de las fotos" to "Search the text in photos",
    "Facturas, carteles y capturas se encuentran por lo que dicen." to "Invoices, signs and screenshots are found by what they say.",
    "Busca por personas" to "Search by people",
    "Prueba «Lucía y Marcos en la playa» o «solo Lucía»." to "Try “Lucía and Marcos at the beach” or “only Lucía”.",
    "Álbumes inteligentes" to "Smart albums",
    "Guarda cualquier búsqueda como álbum: se llena solo con las fotos nuevas que encajen." to "Save any search as an album: it fills itself with new photos that match.",
    "Notas y etiquetas" to "Notes and tags",
    "Abre una foto, pulsa ⓘ y escribe una nota o #etiquetas. Luego las encuentras en el buscador." to "Open a photo, tap ⓘ and write a note or #tags. Then find them in search.",
    "Personas" to "People",
    "Lumi junta las caras de cada persona. Ponle nombre una vez y ya está." to "Lumi groups each person's faces. Name them once and you're done.",
    "¿Son la misma persona?" to "Are they the same person?",
    "Desliza como unas cartas para decir si dos caras son de la misma persona." to "Swipe like cards to say whether two faces are the same person.",
    "Cómo ha crecido" to "How they've grown",
    "En el perfil de una persona, su cara a lo largo de los años." to "On a person's profile, their face over the years.",
    "Cámara Lumi" to "Lumi Camera",
    "Una cámara con Lumi Auto: aclara y da color a cada foto al guardarla." to "A camera with Lumi Auto: brightens and adds colour to every photo as it's saved.",
    "Ráfaga que elige sola" to "Burst that picks for you",
    "Mantén pulsado el disparador: haz una ráfaga y Lumi guarda solo la mejor." to "Hold the shutter: take a burst and Lumi keeps only the best.",
    "Noche y HDR" to "Night and HDR",
    "Con poca luz o contraluz, Lumi junta varias fotos en una." to "In low light or backlight, Lumi merges several shots into one.",
    "Modo Pro" to "Pro mode",
    "Controla ISO, velocidad, enfoque y color con ruedas de muescas." to "Control ISO, speed, focus and colour with notched dials.",
    "Lector de QR" to "QR reader",
    "Lee QR y códigos de barras; avisa de enlaces dudosos y conecta al wifi." to "Reads QR and barcodes; warns about suspicious links and joins wifi.",
    "Dispara cuando sonríen" to "Shoots when they smile",
    "El modo Inteligente espera a que todos sonrían y el móvil esté quieto." to "Smart mode waits until everyone smiles and the phone is still.",
    "Timelapse" to "Timelapse",
    "Una foto cada pocos segundos y Lumi monta el vídeo acelerado." to "A photo every few seconds and Lumi builds the sped-up video.",
    "Cámara privada" to "Private camera",
    "Las fotos van cifradas a la carpeta privada, nunca a la galería." to "Photos go encrypted to the private folder, never to the gallery.",
    "Lumi como cámara del teléfono" to "Lumi as the phone's camera",
    "Elígela como cámara y toca «Siempre»: otras apps también la usarán." to "Choose it as your camera and tap “Always”: other apps will use it too.",
    "Retrato en cualquier móvil" to "Portrait on any phone",
    "El modo Retrato desenfoca el fondo aunque tu móvil no tenga modo retrato." to "Portrait mode blurs the background even if your phone has no portrait mode.",
    "Editor de fotos" to "Photo editor",
    "Recorte, luz, color, curvas, tonos y detalle. Siempre guarda una copia." to "Crop, light, colour, curves, tones and detail. It always saves a copy.",
    "Retocar solo una zona" to "Retouch just one area",
    "Con un degradado, un círculo o un pincel: oscurece un cielo o aclara una cara." to "With a gradient, a circle or a brush: darken a sky or brighten a face.",
    "Borrar cosas pequeñas" to "Erase small things",
    "Pinta encima de una mota, un cable o un papel y desaparece." to "Paint over a speck, a cable or a piece of paper and it disappears.",
    "Retoque de caras" to "Face retouch",
    "Suaviza la piel, ilumina los ojos y quita los ojos rojos con un control." to "Smooths skin, brightens eyes and removes red eye with one control.",
    "Marcos para redes" to "Frames for social media",
    "Un borde blanco, estilo polaroid o con el fondo desenfocado." to "A white border, polaroid style or with a blurred background.",
    "Historial de cambios" to "Edit history",
    "Vuelve a cualquier paso de la edición y retómala más tarde." to "Go back to any step of the edit and pick it up later.",
    "Copiar ajustes" to "Copy adjustments",
    "Copia los ajustes de una foto y pégalos en otras: editas una vez para todas." to "Copy one photo's adjustments and paste them on others: edit once for all.",
    "Mejorar fotos oscuras" to "Improve dark photos",
    "Lumi encuentra las fotos oscuras o apagadas y las mejora en lote." to "Lumi finds dark or dull photos and improves them in a batch.",
    "Quitar el fondo" to "Remove the background",
    "En el menú de una foto: recorta a la persona o al objeto principal." to "In a photo's menu: cuts out the person or main object.",
    "Pegatinas para WhatsApp" to "WhatsApp stickers",
    "Recorta a una persona o mascota y guárdala como pegatina." to "Cut out a person or pet and save it as a sticker.",
    "Datos de la toma" to "Shot details",
    "En la información de la foto: histograma, cámara, ISO, velocidad y apertura." to "In the photo info: histogram, camera, ISO, speed and aperture.",
    "Lupa" to "Magnifier",
    "Mantén el dedo sobre una foto para ver una lupa que amplía lo que hay debajo." to "Hold your finger on a photo to see a magnifier over what is underneath.",
    "Fotos RAW" to "RAW photos",
    "Las fotos DNG se ven con su etiqueta, se comparan con su JPEG y se revelan en el editor." to "DNG photos show a label, can be compared with their JPEG and are developed in the editor.",
    "Fotos en movimiento" to "Motion photos",
    "Mantén el dedo sobre una foto en movimiento y se mueve." to "Hold your finger on a motion photo and it moves.",
    "Editor de vídeo" to "Video editor",
    "Línea de tiempo con fotogramas: divide, quita trozos y reordena." to "Timeline with frames: split, remove pieces and reorder.",
    "Unir vídeos y fotos" to "Join videos and photos",
    "Junta varios vídeos y fotos en uno, con transiciones." to "Put several videos and photos into one, with transitions.",
    "Títulos en el vídeo" to "Titles in the video",
    "Textos animados que aparecen y desaparecen cuando tú digas." to "Animated text that appears and disappears when you say.",
    "Música de fondo" to "Background music",
    "Pon una canción de tu móvil, mezclada con el sonido y con fundido al final." to "Add a song from your phone, mixed with the sound and fading out at the end.",
    "Formato para redes" to "Format for social media",
    "Vertical o cuadrado con el fondo desenfocado en vez de franjas negras." to "Vertical or square with a blurred background instead of black bars.",
    "Velocidad por tramos" to "Speed by section",
    "Cámara lenta solo en un momento, o acelera lo aburrido." to "Slow motion for just one moment, or speed up the boring part.",
    "Doble velocidad" to "Double speed",
    "Mantén el dedo en un vídeo para verlo al doble de velocidad." to "Hold your finger on a video to watch it at double speed.",
    "Saltar en un vídeo" to "Skip in a video",
    "Dos toques a un lado saltan 10 segundos; sigue tocando para sumar." to "Two taps on a side skip 10 seconds; keep tapping to add more.",
    "Escáner de documentos" to "Document scanner",
    "Endereza y limpia cada hoja y la guarda en PDF con el texto dentro." to "Straightens and cleans each page and saves a PDF with the text inside.",
    "DNI en una hoja" to "ID on one page",
    "Escanea las dos caras de un documento y salen en una sola página." to "Scan both sides of a document and they come out on a single page.",
    "Firmar documentos" to "Sign documents",
    "Dibuja tu firma una vez y ponla en cualquier PDF." to "Draw your signature once and place it on any PDF.",
    "Carpeta privada" to "Private folder",
    "Fotos cifradas que solo se abren con tu huella o tu PIN." to "Encrypted photos that only open with your fingerprint or PIN.",
    "PIN señuelo" to "Decoy PIN",
    "Si te obligan a abrir la carpeta privada, otro PIN abre una carpeta falsa." to "If you're forced to open the private folder, another PIN opens a fake one.",
    "Tu DNI, bajo llave" to "Your ID, under lock",
    "Lumi encuentra documentos, tarjetas y contraseñas en tus fotos para protegerlos." to "Lumi finds documents, cards and passwords in your photos to protect them.",
    "Modo enseñar" to "Show mode",
    "Presta el móvil: solo se ven las fotos que elijas y no se puede salir." to "Lend your phone: only the photos you choose are visible and it can't be left.",
    "Enviar sin ubicación" to "Send without location",
    "En el menú de una foto: envíala sin los datos de dónde se hizo." to "In a photo's menu: send it without the data of where it was taken.",
    "Lumi en blanco en recientes" to "Lumi blank in recents",
    "Al cambiar de app, Lumi no enseña tus fotos en la vista de apps recientes." to "When you switch apps, Lumi doesn't show your photos in the recent apps view.",
    "Carpetas de álbumes" to "Album folders",
    "Mantén pulsado un álbum para meterlo en una carpeta como Viajes o Familia." to "Hold an album to put it in a folder like Trips or Family.",
    "Arrastrar a un álbum" to "Drag to an album",
    "Elige fotos y arrástralas a una bandeja de álbumes." to "Pick photos and drag them onto an album tray.",
    "Corregir fechas" to "Fix dates",
    "Arregla la fecha de las fotos de WhatsApp o escaneadas." to "Fix the date of WhatsApp or scanned photos.",
    "Fotos temporales" to "Temporary photos",
    "Marca una foto para que se borre sola: el ticket del parking, una talla." to "Mark a photo to delete itself: the parking ticket, a size check.",
    "Agitar para deshacer" to "Shake to undo",
    "Tras borrar o mover algo, agita el móvil y lo deshace." to "After deleting or moving something, shake the phone to undo it.",
    "Repaso rápido" to "Quick review",
    "Desliza para borrar o quedarte con cada foto, como unas cartas." to "Swipe to delete or keep each photo, like cards.",
    "Liberar espacio" to "Free up space",
    "Copias, parecidas, vídeos grandes y capturas antiguas, con confeti al terminar." to "Copies, similar photos, big videos and old screenshots, with confetti at the end.",
    "Borrar sin que Android pregunte" to "Delete without Android asking",
    "Concede la gestión multimedia y Lumi borra sin pedir permiso cada vez." to "Grant media management and Lumi deletes without asking each time.",
    "Tu mes en fotos" to "Your month in photos",
    "El primer día de cada mes, el resumen del anterior como una historia." to "In the first days of each month, a summary of the last one as a story.",
    "Los primeros días de cada mes, el resumen del anterior como una historia." to "In the first days of each month, a summary of the last one as a story.",
    "Tu año en fotos" to "Your year in photos",
    "Tu año día a día, con sitios, personas y temas." to "Your year day by day, with places, people and topics.",
    "Widgets" to "Widgets",
    "Foto, mosaico, recuerdos, cámara y atajos en tu pantalla de inicio." to "Photo, mosaic, memories, camera and shortcuts on your home screen.",
    "Fondo que cambia solo" to "Wallpaper that changes itself",
    "Tus favoritas o un álbum de fondo de pantalla, cada día." to "Your favourites or a wallpaper album, every day.",
    "Calendario" to "Calendar",
    "Salta a cualquier día tocando el calendario de la pantalla Fotos." to "Jump to any day by tapping the calendar on the Photos screen.",
    "Recorrido por Lumi" to "Tour of Lumi",
    "El recorrido con todo lo que hace Lumi, cuando quieras." to "The tour of everything Lumi does, whenever you like.",

    // Descubre Lumi, consejos y globos de ayuda
    "Descubre Lumi" to "Discover Lumi",
    "Buscar una función" to "Search for a feature",
    "Nada con ese nombre" to "Nothing with that name",
    "Prueba con otra palabra, por ejemplo «fecha» o «vídeo»." to "Try another word, for example “date” or “video”.",
    "Probar" to "Try",
    "Otra vez" to "Again",
    "Entendido" to "Got it",
    "Volver a ver los consejos" to "Show the tips again",
    "Los «¿Sabías que…?» y los globos de ayuda de cada pantalla" to "The “Did you know…?” cards and the help bubbles on each screen",
    "Verás de nuevo los consejos" to "You'll see the tips again",
    "Desliza hacia arriba para ver su información, su nota y sus etiquetas. Pellizca o toca dos veces para acercar." to "Swipe up to see its info, note and tags. Pinch or double-tap to zoom.",
    "Mantén pulsada una foto y arrastra el dedo para elegir varias de golpe. Pellizca para cambiar el zoom." to "Hold a photo and drag your finger to pick several at once. Pinch to change the zoom.",
    "Mantén pulsado un álbum para fijarlo arriba, bloquearlo, ocultarlo o meterlo en una carpeta." to "Hold an album to pin it at the top, lock it, hide it or put it in a folder.",
    "Prueba «Lucía en la playa» o «tickets»: Lumi entiende personas, sitios y cosas. Guarda la búsqueda como álbum inteligente." to "Try “Lucía at the beach” or “receipts”: Lumi understands people, places and things. Save the search as a smart album.",

    // Álbumes inteligentes
    "✦ Álbumes inteligentes" to "✦ Smart albums",
    "✦ Guardar como álbum inteligente" to "✦ Save as smart album",
    "Álbum inteligente" to "Smart album",
    "Quitar este álbum" to "Remove this album",
    "Aún sin fotos" to "No photos yet",
    "Búsqueda guardada" to "Saved search",

    // Notas, etiquetas, fecha y fotos temporales
    "Nota y etiquetas" to "Note and tags",
    "Escribe algo de esta foto o ponle #etiquetas: luego las encuentras en el buscador." to "Write something about this photo or add #tags: then find them in search.",
    "Una nota sobre esta foto…" to "A note about this photo…",
    "Añadir etiqueta" to "Add tag",
    "Las que ya has usado" to "The ones you've already used",
    "Solo se guardan en tu teléfono, no dentro del archivo." to "They are only stored on your phone, not inside the file.",
    "Por ejemplo: reformas" to "For example: renovations",
    "Datos de la toma" to "Shot details",
    "Cambiar" to "Change",
    "Fecha" to "Date",
    "Poner esta fecha" to "Set this date",
    "Foto temporal" to "Temporary photo",
    "Se manda a la papelera hoy" to "Goes to the trash today",
    "Se manda a la papelera mañana" to "Goes to the trash tomorrow",
    "Se mandará a la papelera dentro de un día" to "Will go to the trash in a day",
    "Borrar sola…" to "Delete automatically…",
    "Borrar sola dentro de unos días…" to "Delete automatically in a few days…",
    "Borrar sola dentro de…" to "Delete automatically in…",
    "La foto pasará a la papelera cuando acabe el plazo, donde sigue 30 días." to "The photo will go to the trash when time is up, where it stays 30 days.",
    "Una foto temporal ha caducado" to "A temporary photo has expired",
    "Marcaste esta foto para que se borrara sola. Va a la papelera, donde sigue 30 días. Nada se borra sin tu permiso." to "You marked this photo to delete itself. It goes to the trash, where it stays 30 days. Nothing is deleted without your permission.",
    "Marcaste estas fotos para que se borraran solas. Van a la papelera, donde siguen 30 días. Nada se borra sin tu permiso." to "You marked these photos to delete themselves. They go to the trash, where they stay 30 days. Nothing is deleted without your permission.",
    "A la papelera" to "To the trash",
    "Un día más" to "One more day",
    "Conservar" to "Keep",
    "foto etiquetada" to "photo tagged", "fotos etiquetadas" to "photos tagged",
    "foto con su fecha arreglada" to "photo with its date fixed", "fotos con su fecha arreglada" to "photos with their date fixed",
    "foto temporal a la papelera" to "temporary photo to the trash", "fotos temporales a la papelera" to "temporary photos to the trash",
    "foto no dice" to "photo doesn't say", "fotos no dicen" to "photos don't say",
    "Pegar los ajustes copiados del editor" to "Paste the adjustments copied in the editor",
    "Borrar sola dentro de unos días…" to "Delete automatically in a few days…",
    "Etiquetar…" to "Tag…",
    "Etiquetar" to "Tag",
    "1 día" to "1 day",
    "Elige fotos para pegarles los ajustes" to "Pick photos to paste the adjustments on",
    "No se pudo guardar ninguna copia" to "No copy could be saved",
    "copia guardada con esos ajustes" to "copy saved with those adjustments", "copias guardadas con esos ajustes" to "copies saved with those adjustments",

    // Fechas
    "Fechas por revisar" to "Dates to review",
    "Cada foto en su día" to "Every photo on its day",
    "Todo en su día" to "Everything on its day",
    "No hay fotos con la fecha equivocada ni fotos sin fecha." to "There are no photos with the wrong date or without a date.",
    "Con otra fecha en el nombre" to "With another date in the name",
    "Sin fecha" to "No date",
    "Arreglar" to "Fix",
    "Elegir todas" to "Select all",
    "Elige fotos" to "Pick photos",

    // Tu mes en fotos
    "Tu mes en fotos" to "Your month in photos",
    "No hay fotos de ese mes, sin contar capturas de pantalla." to "There are no photos from that month, not counting screenshots.",
    "día con fotos" to "day with photos", "días con fotos" to "days with photos",
    "Tu mejor día" to "Your best day",
    "Lo mejor del mes" to "Best of the month",
    "Con quién estuviste" to "Who you were with",
    "Dónde estuviste" to "Where you were",
    "Lo mejor, las personas y los sitios del mes pasado" to "The best, the people and the places of last month",
    "Hacer un vídeo con música" to "Make a video with music",

    // Pegatinas
    "Pegatinas" to "Stickers",
    "Para WhatsApp" to "For WhatsApp",
    "Mis pegatinas de Lumi" to "My Lumi stickers",
    "Pegatina de Lumi" to "Lumi sticker",
    "Añadir a WhatsApp" to "Add to WhatsApp",
    "No se pudo abrir WhatsApp. Comprueba que lo tienes instalado y actualizado." to "Couldn't open WhatsApp. Check that it is installed and up to date.",
    "Las pegatinas se guardan solo en Lumi; WhatsApp las lee desde aquí, sin conexión." to "Stickers are stored only in Lumi; WhatsApp reads them from here, offline.",
    "Emoji con el que WhatsApp la sugiere" to "Emoji WhatsApp suggests it with",
    "Pegatina" to "Sticker",
    "Pegatina añadida a tu paquete" to "Sticker added to your pack",
    "El paquete está lleno: quita alguna pegatina antes" to "The pack is full: remove a sticker first",
    "Crear pegatina" to "Create sticker",
    "Crear pegatina para WhatsApp" to "Create WhatsApp sticker",
    "Con borde blanco" to "With white border",
    "Sin borde" to "No border",
    "Emoji" to "Emoji",
    "Quitar" to "Remove",
    "Listo" to "Done",
    "Separando del fondo…" to "Separating from the background…",
    "Elige una foto\ny ⋯ → Crear pegatina" to "Pick a photo\nthen ⋯ → Create sticker",

    // RAW
    "Comparar con su JPEG" to "Compare with its JPEG",
    "Comparar con su RAW" to "Compare with its RAW",
    "Tiene su JPEG: compararlos" to "Has its JPEG: compare them",
    "Tiene su RAW: compararlos" to "Has its RAW: compare them",
    "Revelar RAW" to "Develop RAW",
    "Revelado RAW" to "RAW development",

    // Editor de fotos
    "Foto original" to "Original photo",
    "Retomada tu edición anterior" to "Picked up your previous edit",
    "Edición retomada" to "Edit resumed",
    "Cambio" to "Change",
    "Recorte y giro" to "Crop and rotate",
    "Curvas, tonos o detalle" to "Curves, tones or detail",
    "Zonas" to "Areas",
    "Caras" to "Faces",
    "Marco" to "Frame",
    "Sin marco" to "No frame",
    "Blanco" to "White",
    "Negro" to "Black",
    "Polaroid" to "Polaroid",
    "Desenfocado 1:1" to "Blurred 1:1",
    "Desenfocado 4:5" to "Blurred 4:5",
    "Degradado" to "Gradient",
    "Círculo" to "Circle",
    "Pincel" to "Brush",
    "Grosor" to "Thickness",
    "Retoque" to "Retouch",
    "Exposición" to "Exposure",
    "Recuperar luces" to "Recover highlights",
    "Abrir sombras" to "Open shadows",
    "No se ve ninguna cara en esta foto (o Google Play aún está descargando el detector)." to "No face is visible in this photo (or Google Play is still downloading the detector).",
    "Una cara encontrada" to "One face found",
    "Buscando caras…" to "Looking for faces…",
    "Copiar ajustes" to "Copy adjustments",
    "Pegar ajustes" to "Paste adjustments",
    "Ajustes copiados. Pégalos en otra foto o en varias a la vez desde la selección." to "Adjustments copied. Paste them on another photo or on several at once from the selection.",
    "Ajustes pegados" to "Adjustments pasted",
    "Poniendo el marco…" to "Putting on the frame…",
    "Pinta sobre lo que quieras quitar: una mota, un cable, un papel. Rellena con lo que hay alrededor, así que va mejor con cosas pequeñas." to "Paint over what you want to remove: a speck, a cable, a piece of paper. It fills in from what's around, so it works best on small things.",
    "Nada pintado" to "Nothing painted",
    "Deshacer el último trazo" to "Undo the last stroke",
    "Quitar todo lo pintado" to "Remove everything painted",
    "Añade una zona: un degradado (para un cielo), un círculo (para una cara) o un pincel. Luego arrastra sobre la foto y ajusta luz, contraste, color y calidez solo ahí." to "Add an area: a gradient (for a sky), a circle (for a face) or a brush. Then drag over the photo and adjust light, contrast, colour and warmth only there.",
    "Arrastra sobre la foto: el efecto es total en el punto de salida y se apaga hacia donde sueltas." to "Drag over the photo: the effect is full at the starting point and fades out where you let go.",
    "Arrastra desde el centro hacia fuera para dar tamaño al círculo." to "Drag from the centre outwards to size the circle.",
    "Pinta las partes que quieres ajustar." to "Paint the parts you want to adjust.",
    "Borrar lo pintado" to "Erase what's painted",
    "Quitar esta zona" to "Remove this area",
    "Suaviza la piel sin quitar los detalles y da luz a los ojos. Con un solo control." to "Smooths skin without losing detail and brightens the eyes. With a single control.",
    "Quitar ojos rojos" to "Remove red eye",
    "El marco se pone al guardar, después del recorte. «Desenfocado» rellena con la misma foto difuminada, sin franjas negras." to "The frame is added when saving, after the crop. “Blurred” fills with the same photo blurred, with no black bars.",
    "Este RAW conserva margen en luces y sombras: recupera lo que un JPEG ya habría perdido." to "This RAW keeps headroom in highlights and shadows: it recovers what a JPEG would have already lost.",
    "Android entrega este RAW ya revelado a 8 bits, así que el margen es el de un JPEG: los ajustes valen, pero con menos recorrido." to "Android hands over this RAW already developed at 8 bits, so the headroom is that of a JPEG: the adjustments work, but with less range.",
    "Abriendo el RAW…" to "Opening the RAW…",
    "Historial de cambios" to "Edit history",
    "Toca un paso para volver a cómo estaba la foto entonces. Lo que hagas después se añade al final." to "Tap a step to go back to how the photo was then. Whatever you do next is added at the end.",
    "Ahora" to "Now",
    "Cerrar" to "Close",

    // Editor de vídeo
    "Recortar al centro" to "Crop to centre",
    "Fondo desenfocado" to "Blurred background",
    "Franjas negras" to "Black bars",
    "Con caja" to "With box",
    "Dorado" to "Gold",
    "Rosa" to "Pink",
    "Sencillo" to "Plain",
    "Aparece" to "Fade in",
    "Sube" to "Rise",
    "Rebote" to "Pop",
    "Fijo" to "Fixed",
    "Arriba" to "Top",
    "Centro" to "Centre",
    "Abajo" to "Bottom",
    "Corte" to "Cut",
    "Fundido" to "Fade",
    "Deslizar" to "Slide",
    "Acercar" to "Zoom in",
    "9:16 vertical" to "9:16 vertical",
    "1:1 cuadrado" to "1:1 square",
    "16:9 horizontal" to "16:9 horizontal",
    "Cortar" to "Cut",
    "Velocidad" to "Speed",
    "Añadir" to "Add",
    "Textos" to "Text",
    "Música" to "Music",
    "Formato" to "Format",
    "Color" to "Colour",
    "Sonido" to "Sound",
    "Deshacer" to "Undo",
    "No se puede leer esa canción" to "That song can't be read",
    "Dividir aquí" to "Split here",
    "Lleva el reproductor a este trozo para dividirlo" to "Move the player to this clip to split it",
    "Elige un punto más lejos de los extremos" to "Pick a point farther from the ends",
    "Quitar este trozo" to "Remove this clip",
    "Tiene que quedar al menos un trozo" to "At least one clip must remain",
    "← Mover" to "← Move",
    "Mover →" to "Move →",
    "Las fotos no tienen velocidad: cambia cuánto duran en «Cortar»." to "Photos have no speed: change how long they last in “Cut”.",
    "Este trozo a velocidad normal" to "This clip at normal speed",
    "Poner esta velocidad a todos los trozos" to "Use this speed on all clips",
    "Cada trozo puede tener su velocidad. El sonido se ajusta sin volverse agudo ni grave." to "Each clip can have its own speed. The sound adjusts without turning high or low pitched.",
    "Añadir vídeos o fotos de la galería" to "Add videos or photos from the gallery",
    "Igual a todos" to "Same for all",
    "«Fundido» enciende la imagen desde negro, «Deslizar» la trae de un lado y «Acercar» la acerca. Se ven al guardar." to "“Fade” brings the image up from black, “Slide” brings it in from the side and “Zoom in” brings it closer. They show when saving.",
    "Añadir un texto aquí" to "Add text here",
    "Cambiar el texto" to "Edit the text",
    "Lleva el reproductor al momento en que quieras el texto y pulsa «Añadir un texto aquí»." to "Move the player to the moment you want the text and tap “Add text here”.",
    "Elegir una canción del móvil" to "Pick a song from your phone",
    "Suena de fondo junto al sonido original. Con «Sonido» bajas o quitas el original." to "It plays in the background along with the original sound. With “Sound” you lower or remove the original.",
    "Se apaga poco a poco al final" to "Fades out at the end",
    "Quitar la canción" to "Remove the song",
    "Si lo grabado no tiene esa forma: el fondo desenfocado rellena los lados con la misma imagen difuminada, en vez de franjas negras." to "If the footage isn't that shape: the blurred background fills the sides with the same image blurred, instead of black bars.",
    "Quitar ajustes" to "Remove adjustments",
    "Lumi Auto" to "Lumi Auto",
    "Luz" to "Light",
    "Contraste" to "Contrast",
    "Calidez" to "Warmth",
    "Curva" to "Curve",
    "No se pudo mirar la imagen" to "Couldn't look at the image",
    "Con sonido" to "With sound",
    "Sin sonido" to "No sound",
    "El vídeo nuevo se guarda sin el sonido original" to "The new video is saved without the original sound",
    ", solo con la canción." to ", with only the song.",
    "Texto en el vídeo" to "Text in the video",
    "Por ejemplo: Verano 2026" to "For example: Summer 2026",
    "Elige vídeos o fotos" to "Pick videos or photos",
    "Girar 90°" to "Rotate 90°",
    "Espejo" to "Mirror",
    "trozo" to "clip", "trozos" to "clips",
    // Pulido: vibración, deshacer, selección, enviar, búsquedas fijadas, estado y errores
    "Nota guardada" to "Note saved",
    "Ya está fijada" to "Already pinned",
    "Búsqueda fijada arriba" to "Search pinned at the top",
    "Atajo quitado" to "Shortcut removed",
    "Álbum inteligente quitado" to "Smart album removed",
    "Fijadas" to "Pinned",
    "📌 Fijar" to "📌 Pin",
    "Analizando las fotos de nuevo, poco a poco" to "Analysing your photos again, bit by bit",
    "Elegir" to "Select",
    "Las parecidas" to "Similar ones",
    "Las de este día" to "From this day",
    "Todas" to "All",
    "Invertir" to "Invert",
    "Quedan unos segundos para deshacer" to "A few seconds left to undo",
    "Vibraciones" to "Vibration",
    "Un toque suave al elegir, un tic en las ruedas y un golpe distinto al soltar y al borrar." to "A soft tap when selecting, a tick on the dials and a different thump when dropping and deleting.",
    "Estado de Lumi" to "Lumi status",
    "Cuánto ocupa, qué ha mirado, limpiar la caché y volver a analizar" to "How much space it uses, what it has looked at, clear the cache and re-analyse",
    "Enviar vídeo" to "Share video",
    "Enviar foto" to "Share photo",
    "Reducir para enviar por chat" to "Shrink to send in chats",
    "Copias de 1600 puntos: pesan mucho menos y se ven igual en el móvil." to "1600-pixel copies: they weigh much less and look the same on a phone.",
    "Más opciones" to "More options",
    "Informe de fallo de Lumi" to "Lumi crash report",
    "Lumi se cerró la última vez" to "Lumi closed unexpectedly last time",
    "Si quieres, envía este informe y lo arreglamos. Lleva la versión, el modelo del móvil y las líneas del fallo; no lleva fotos, nombres ni datos tuyos. No se envía nada solo." to "If you like, send this report and we'll fix it. It carries the version, the phone model and the lines of the error; no photos, names or personal data. Nothing is sent on its own.",
    "Enviar informe" to "Send report",
    "Descartar" to "Dismiss",
    "Lo que Lumi ha mirado" to "What Lumi has looked at",
    "Fotos y vídeos" to "Photos and videos",
    "Fotos ya analizadas" to "Photos already analysed",
    "Fotos con gente" to "Photos with people",
    "Personas encontradas" to "People found",
    "Etiquetas y notas" to "Tags and notes",
    "Lo que ocupa en el teléfono" to "What it uses on the phone",
    "Midiendo…" to "Measuring…",
    "Miniaturas y copias temporales" to "Thumbnails and temporary copies",
    "Índice y caras" to "Index and faces",
    "Otros datos de Lumi" to "Other Lumi data",
    "Limpiar la caché" to "Clear the cache",
    "Caché limpia" to "Cache cleared",
    "La caché se vuelve a llenar sola: no se pierde ninguna foto, solo habrá que esperar un momento a ver las miniaturas." to "The cache refills by itself: no photo is lost, you'll just wait a moment to see thumbnails.",
    "Si algo se ve raro" to "If something looks off",
    "Volver a analizar borra lo que Lumi sabe de tus fotos (cosas, texto, lugares) y lo lee otra vez, despacio y en segundo plano. Tus fotos, las personas y la carpeta privada no se tocan." to "Re-analysing clears what Lumi knows about your photos (things, text, places) and reads it again, slowly and in the background. Your photos, people and private folder are not touched.",
    "Volver a analizar las fotos" to "Re-analyse the photos",
    "¿Volver a analizar?" to "Re-analyse?",
    "Volver a analizar" to "Re-analyse",
    "Mientras termina, el buscador irá encontrando cosas poco a poco. Gasta algo de batería." to "While it finishes, search will find things bit by bit. It uses some battery.",
    "Último cierre inesperado" to "Last unexpected close",
    "Selección inteligente" to "Smart selection",
    "Elige una foto y toca «Las parecidas», «Las de este día», «Todas» o «Invertir»." to "Pick a photo and tap “Similar ones”, “From this day”, “All” or “Invert”.",
    "Enviar en dos toques" to "Share in two taps",
    "La hoja «Enviar» pone arriba tus apps de siempre y puede reducir las fotos para el chat." to "The Share sheet puts your usual apps on top and can shrink photos for chats.",
    "Búsquedas fijadas" to "Pinned searches",
    "En el buscador, pulsa «📌 Fijar» y la búsqueda queda como atajo arriba." to "In search, tap “📌 Pin” and the search stays as a shortcut at the top.",
    "Cuánto ocupa, qué ha mirado, limpiar la caché y volver a analizar si algo se ve raro." to "How much space it uses, what it has looked at, clear the cache and re-analyse if something looks off.",
)

internal val PATTERNS_MORE: List<Pair<Regex, (List<String>) -> String>> = listOf(
    rule("Álbum inteligente «(.+)» guardado") { "Smart album “${it[1]}” saved" },
    rule("(\\d+) de (\\d+) descubiertas") { "${it[1]} of ${it[2]} discovered" },
    rule("(\\d+) de (\\d+) funciones descubiertas: búscalas y pruébalas") { "${it[1]} of ${it[2]} features discovered: look them up and try them" },
    rule("¿Sabías que…\\? (.+)") { "Did you know…? ${tr(it[1])}" },
    rule("Tu (.+) en fotos") { "Your ${tr(it[1].replaceFirstChar { c -> c.uppercase() })} in photos" },
    rule("Se manda a la papelera dentro de (\\d+) días") { "Goes to the trash in ${it[1]} days" },
    rule("Se mandará a la papelera dentro de (\\d+) días") { "Will go to the trash in ${it[1]} days" },
    rule("Las (\\d+) fotos pasarán a la papelera cuando acabe el plazo, donde siguen 30 días\\.") { "The ${it[1]} photos will go to the trash when time is up, where they stay 30 days." },
    rule("(\\d+) fotos temporales han caducado") { "${it[1]} temporary photos have expired" },
    rule("Etiquetar (\\d+)") { "Tag ${it[1]}" },
    rule("Poner fecha a (\\d+)") { "Set date for ${it[1]}" },
    rule("Arreglar las (\\d+)") { "Fix all ${it[1]}" },
    rule("Y (\\d+) más: «Arreglar las (\\d+)» las cambia todas\\.") { "And ${it[1]} more: “Fix all ${it[2]}” changes them all." },
    rule("(.+) de WhatsApp o descargadas salen con la fecha en que llegaron\\. El nombre del archivo dice cuándo se hicieron de verdad\\.") {
        "${it[1]} from WhatsApp or downloaded show the date they arrived. The file name says when they were really taken."
    },
    rule("(.+) cuándo se hicieron \\(escaneos, por ejemplo\\)\\. Elige las que quieras y ponles una fecha\\.") {
        "${it[1]} when they were taken (scans, for example). Pick the ones you want and give them a date."
    },
    rule("Nada en (.+)") { "Nothing in ${it[1]}" },
    rule("(\\d+) caras encontradas") { "${it[1]} faces found" },
    rule("Historial") { "History" },
    rule("Necesitas al menos (\\d+) pegatinas para añadir el paquete a WhatsApp\\. Abre una foto, pulsa ⋯ y elige «Crear pegatina»\\.") {
        "You need at least ${it[1]} stickers to add the pack to WhatsApp. Open a photo, tap ⋯ and choose “Create sticker”."
    },
    rule("(\\d+) de (\\d+)\\. Pulsa una pegatina para cambiar su emoji o quitarla\\.") { "${it[1]} of ${it[2]}. Tap a sticker to change its emoji or remove it." },
    rule("Guardando (\\d+) %") { "Saving ${it[1]}%" },
    rule("Guardando el vídeo nuevo… (\\d+) %") { "Saving the new video… ${it[1]}%" },
    rule("(\\d+) trozos?") { "${it[1]} clip${if (it[1] == "1") "" else "s"}" },
    rule("(Foto|Vídeo) (\\d+) de (\\d+)") { "${if (it[1] == "Foto") "Photo" else "Video"} ${it[2]} of ${it[3]}" },
    rule("dura (.+)") { "lasts ${it[1]}" },
    rule("Dura (.+) s") { "Lasts ${it[1].replace(',', '.')} s" },
    rule("Del (.+) al (.+) del vídeo original") { "From ${it[1]} to ${it[2]} of the original video" },
    rule("Este trozo en cámara lenta: (.+)") { "This clip in slow motion: ${it[1]}" },
    rule("Este trozo más rápido: (.+)") { "This clip faster: ${it[1]}" },
    rule("Cómo entra el trozo (\\d+)") { "How clip ${it[1]} comes in" },
    rule("Se ve de (.+) a (.+)") { "Shown from ${it[1]} to ${it[2]}" },
    rule("Volumen de la canción: (\\d+) %") { "Song volume: ${it[1]}%" },
    rule("Empieza en el minuto (.+)") { "Starts at ${it[1]}" },
    rule("Volumen del sonido original: (\\d+) %") { "Original sound volume: ${it[1]}%" },
    rule("(\\d+) elegidos") { "${it[1]} chosen" },
    rule("Versión (.+)") { "Version ${it[1]}" },
    rule("Espera (.+) para volver a probar") { "Wait ${it[1]} before trying again" },
    rule("Demasiados intentos\\. Prueba otra vez dentro de (.+)") { "Too many attempts. Try again in ${it[1]}" },
    rule("Enviar (\\d.*)") { "Share ${it[1]}" },
    rule("Filtro «(.+)» borrado") { "Filter “${it[1]}” deleted" },
)

private fun rule(pattern: String, build: (List<String>) -> String) = Regex(pattern) to build
